import { PropuestaValor } from "./propuesta-valor";
import { TipsValor } from "./tips-valor";
import { ButtonGeneral } from "./button-general";
import { NavBar } from "./nav-bar";
import { BannerMain } from "./banner-main";
import { FooterMain } from "./footer-main";
import { MiAgenda } from "./mi-agenda";
import { RefillIcon } from "./refill-icon";
import { TableContent } from "./table-content";